add constructor to accept nullable objects
Before this commit, having a null element in the list usually caused
it to throw a NoSuchMethodError because null does not have ´compareTo`
method (wich is kinda obvious)